# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9438e23f1e346239d6392565a83a3839afd0029c5b3f74c2f97d981235479c4713294b8359834f451966b5da080b032d4c89229c1b4afd0de5233d5834e918bd

test:
  secret_key_base: 1c9871aa47dcc192698365c64cc78d6375fc94eb72b6d6e17afb8308110342295c464060674ae85f2cb7d85f81a0bd38fe0f6fcb49bdd5c708d4935e66f40407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
